# Generated by Django 4.0.4 on 2022-05-21 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoty',
        ),
        migrations.DeleteModel(
            name='Catergory',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
